### ISSUE TITLE
404 on blazor-analytics.js

### ISSUE THREAD

**Issue by commissionsio** [isc30/blazor-analytics#10]
3.0.0.2 build from Nuget
Running server side blazor 3.1 (.net core 3.1.1)

Title says it all, getting a 404 for the blazor-analytics.js
Roll back to 3.0.0 and now blazor-analytics.js comes through fine, everything else seems fine so far.

**Comment by isc30** [comment]
Hi, thanks for reporting this :smile: 
The package was generated by GitHub Actions and it doesn't pick up the TypeScript compilation properly. Will fix it asap.

**Comment by isc30** [comment]
This is solved in 3.0.1 now.
The NuGet version is automatically calculated and TypeScript is getting compiled before packing.

**Comment by commissionsio** [comment]
Just grabbed latest 3.0.1,  still 404'ing on the js.   I cleared build, cache etc reinstalled the package from nothing.  Still occurs.

**Comment by isc30** [comment]
Sorry for this, seems like another bug about serverside js not being embedded was reintroduced after this change

**Comment by isc30** [comment]
This issue is fixed in 3.0.2
