### ISSUE TITLE
google tag manager supported or not?

### ISSUE THREAD

**Issue by git37** [isc30/blazor-analytics#14]
the ContainerId seems not be existing...

**Comment by isc30** [comment]
[GTAG is supported](https://github.com/isc30/blazor-analytics/blob/master/src/Blazor.Analytics/GoogleAnalytics/Resources/GoogleAnalyticsInterop.ts#L25). Which feature are you missing?

**Comment by git37** [comment]
Where to place the gtag id?

**Comment by isc30** [comment]
https://github.com/isc30/blazor-analytics#google-analytics-gtag

**Comment by hakenr** [comment]
@isc30 GTAG is not Google Tag Manager, it is Global Site Tag.
See https://measureschool.com/google-tag-manager-vs-global-site-tag/

Global Site Tag is kind of simplified GTM tailor made for GA.
AFAIL, full GTM is not supported by now.
