### ISSUE TITLE
Adding events

### ISSUE THREAD

**Issue by dinonovak** [isc30/blazor-analytics#18]
Hi,
is there possibility to add events?

**Comment by dinonovak** [comment]
HI all,
I have partially add events support, so typescript function is added and it is added to interop.
can you please check if this is OK
https://github.com/dinonovak/blazor-analytics/commit/33028bc57cd40ac3a067e82dc09cc009b0f10540

now what I do not know is how to trigger this from blazor app?
I am exposing it as public Event, but how can I reference it?

I can then create a pull when we make sure that it works.
Also I also updated nugets to 3.1

**Comment by isc30** [comment]
Hi, the commit looks perfectly fine in terms of interop. I guess we should
expose some injectable that is attached to the google analytics component
to call it from wherever we need. Let me know if you need help with that.

>

**Comment by isc30** [comment]
Hi, im working on a PR to add events and access Analytics from any place in the application via injectable

**Comment by isc30** [comment]
Hi, can you confirm that the latest release version works and has all your changes?
Thanks!

**Comment by dinonovak** [comment]
Hi,
So far all is working perfectly, I will switch to nuget for production to verify it also
