### ISSUE TITLE
tsconfig.json included in Nuget release

### ISSUE THREAD

**Issue by JulianBowes** [isc30/blazor-analytics#20]
In v3.1.1 the tsconfig.json file seems to have been accidentally included in the Nuget package. This causes Visual Studio to generate errors when it can't find anything to compile. Deleting tsconfig.json from the nuget package cache suffices as a workaround.

**Comment by isc30** [comment]
Oh no, I'll try to fix it ASAP. Please use the previous version in the
meantime. Shouldn't take too long to get a fix.
Thanks!

**Comment by Stuart88** [comment]
Heh I came here to report the same issue.

Deleting tsconfig did the trick.

Great work anyway, this is so useful for analytics in Blazor. Thanks!!!!!!!!!!! @isc30

**Comment by isc30** [comment]
My plan is to spend some time tomorrow on this, it should be easy: setting `Pack="false"` on that file.
PRs are also welcome if it's urgent

**Comment by isc30** [comment]
Solved as 1.3.2, thanks!
https://github.com/isc30/blazor-analytics/releases/tag/3.1.2
