### ISSUE TITLE
 no registered service of type 'Blazor.Analytics.IAnalytics'

### ISSUE THREAD

**Issue by idimou** [isc30/blazor-analytics#22]
Ivan,

thanks for putting this together. Really handy.

I've followed your instructions to include this in a Blazor client (WASM) project.

I think there is a problem with the <NavigationTracker/> component.
On page load I get an unhandled error in the UI and looking at the browser debugging console I see:
Unhandled exception rendering component: Cannot provide a value for property 'Analytics' on type 'Blazor.Analytics.Components.NavigationTracker'. There is no registered service of type 'Blazor.Analytics.IAnalytics'. 

Any ideas?

**Comment by isc30** [comment]
Hi, did you also call `.AddGoogleAnalytics(GTAG_ID)`?
This step will configure your id and tell the system that you want to use
GTag

**Comment by idimou** [comment]
Yes I had already added 
`services.AddGoogleAnalytics("UA-*******-**");`
in Startup.cs in the server project.

Do I also have to add 
`builder.services.AddGoogleAnalytics("UA-*******-**");` in Program.cs in the client project?

**Comment by isc30** [comment]
Yes, if you plan to use analytics from WASM :)

**Comment by idimou** [comment]
Done. Works now. Thanks!
