### ISSUE TITLE
Unit Testing (Question)

### ISSUE THREAD

**Issue by jochem4207** [isc30/blazor-analytics#23]
Hello, first of all, thank you for building this <3.

I'm using Xunit together with Bunit to write unit tests. (https://bunit.egilhansen.com/docs/providing-input/inject-services-into-components.html#injecting-services-in-c-based-tests)

To 'mock' an service injection they use a concrete class 
`ctx.Services.AddSingleton<IWeatherForecastService>(new WeatherForecastService());`
I tried to 
`ctx.Services.AddSingleton<IAnalytics>(new ?);`

Is there anything I could use for the IAnalytics. My tests now fail due the error 
` System.InvalidOperationException : Cannot provide a value for property 'Analytics' on type 'Pay1Euro.Client.Pages.Counter'. There is no registered service of type 'Blazor.Analytics.IAnalytics'.` 

My question is : In any project of yours, were you able to test this, and how did you do this?

My very basic Counter page that i'm trying to test.

```
@page "/counter"

<h1>Counter</h1>

<p>Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;

    [Inject]
    private Blazor.Analytics.IAnalytics Analytics { get; set; }

    private void IncrementCount()
    {
        currentCount++;
        Analytics.TrackEvent("Increment", currentCount.ToString(), "CountPage");
    }
}
```

**Comment by isc30** [comment]
Hi, the library doesn't provide any `NullAnalytics` for testing, but you
can create it easily by manually implementing the interface or using Moq

**Comment by jochem4207** [comment]
Thank you ! Ive a lot to learn :) Thanks for pointing me in the right direction!
