### ISSUE TITLE
Bug - 404 on blazor-analytics.js

### ISSUE THREAD

**Issue by Swellenator** [isc30/blazor-analytics#24]
Request URL: https://localhost:44379/_content/Blazor-Analytics/blazor-analytics.js
Status Code: 404

I followed all the instructions for server side Blazor. How does the file get out of the nuget package and into the _content folder? I can see the file in wwwroot folder (not in any other folder, just at the root) in solution explorer but it's not actually there on the file system - it's full path is a path to the NuGet folder.

Any ideas of things I can investigate?

**Comment by isc30** [comment]
Hi, which version of blazor, this lib and sdk are you using?

>

**Comment by Swellenator** [comment]
Sorry I should have included that. I do have .NET core 5 installed but I have a global.json to pin it to 3.1.101. Bot sure how to get the blazor version?

 
<PackageReference Include="Blazor-Analytics" Version="3.1.2" />
 

$ dotnet --info
.NET Core SDK (reflecting any global.json):
Version:   3.1.101
Commit:    b377529961

 

Runtime Environment:

OS Name:     Windows
OS Version:  10.0.18363
OS Platform: Windows
RID:         win10-x64

Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

 

Host (useful for support):

  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9
