### ISSUE TITLE
Remove console logs in JavaScript

### ISSUE THREAD

**Issue by Swimburger** [isc30/blazor-analytics#25]
The `console.log` statements are very useful for debugging, but I'd like them to not be logged in production. Can we have a way to opt-in to logging but have it not logged by default?

The library works great btw, thank you!

**Comment by isc30** [comment]
Right, completely forgot about this, thanks for reporting it.
It should be as simple as surrounding the logging with `#if DEBUG`.
Maybe you can open a PR with that? If not, I will make that change ASAP.

**Comment by isc30** [comment]
3.1.3 released
