### ISSUE TITLE
Feature request: switch to turn off 

### ISSUE THREAD

**Issue by sven5** [isc30/blazor-analytics#27]
Hi,

we need a switch to turn on/off Google analytics. The reason behind this is here in Germany we have GDPR that states that the end user must be able to switch off analytics tracking through consenting or rejecting cookies. 
That means when the user doesn't consent to cookie policy the analytics mustn't be activated.
Could you implement this?

Thanks
Sven

**Comment by CobraCalle** [comment]
+1
