### ISSUE TITLE
Disable tracking on private pages

### ISSUE THREAD

**Issue by CrahunGit** [isc30/blazor-analytics#30]
Is there any way to disable tracking certain pages? It would be nice to have some way to disable it when not needed.

**Comment by isc30** [comment]
Yeah, you could hook into the system and avoid the event being triggered on a specific navigation.
If would be as simple as adding a customizable middleware interface there.

Happy to accept PRs :)

**Comment by CrahunGit** [comment]
I've tried to implement your "easy" solution and the pull request is now created. Probably my solution can be improved so feel free to comment me and I'll change it

**Comment by isc30** [comment]
Hi, just saw the PR and yeah that's what I meant, maybe instead of re-enabling it on navigation i would enforce the @page to implement `Dispose` and re-enable it there?

**Comment by isc30** [comment]
Merged in #38 and released as part of [3.7.0](https://github.com/isc30/blazor-analytics/releases/tag/3.7.0)
😄
