### ISSUE TITLE
Event tracking passes arguments incorrectly

### ISSUE THREAD

**Issue by pelshen** [isc30/blazor-analytics#31]
When passing event value/category/label etc the parameters are passed incorrectly. In https://github.com/isc30/blazor-analytics/blob/master/src/Blazor.Analytics/GoogleAnalytics/GoogleAnalyticsStrategy.cs#L63 you call the interop with

```
await _jsRuntime.InvokeAsync<string>(
    GoogleAnalyticsInterop.TrackEvent,
    _trackingId, eventName, eventValue, eventCategory);
```

But in https://github.com/isc30/blazor-analytics/blob/master/src/Blazor.Analytics/GoogleAnalytics/Resources/GoogleAnalyticsInterop.ts#L46 the parameters are in a different order.

```
export function trackEvent(event: string, eventCategory: string, eventLabel: string, eventValue: string)
{
    gtag("event", event, { event_category: eventCategory, event_label: eventLabel, value: eventValue });
    if(this.debug){
        console.log(`[GTAG][Event trigered]: ${event}`);
    }
}
```

Looking at the history it seems there were two functions for trackEvent in `GoogleAnalyticsInterop.ts` but one was removed in https://github.com/isc30/blazor-analytics/commit/36b752f0b1a6403c7cc2f4e8fee38f65c9db7c5e#diff-6cdb5d4488ebfb7b2a0f7d2e59fea40eea0d17ed2bf53c4f5186d16950b06d9e. The removed one matched the arguments being passed in correctly.

Not sure how you want to resolve this but should be quite straightforward. Let me know if you'd like a pull request for it.

**Comment by Enritski** [comment]
It would be great to get this fixed.

**Comment by isc30** [comment]
Hi, I'm quite busy lately so feel free to open a PR and I will tick it ASAP

**Comment by Enritski** [comment]
Ok, I have a PR ready, but don't seem to have the necessary permissions to submit it.

**Comment by isc30** [comment]
Hi, @Enritski  you can open a fork for that PR or I just invited you as an official collaborator in this repo
