### ISSUE TITLE
How to track custom event?

### ISSUE THREAD

**Issue by ErikHen** [isc30/blazor-analytics#33]
Is it possible to track an event like this for example:
https://developers.google.com/gtagjs/reference/ga4-events#select_content

Why is "eventValue" an integer for TrackEvent (https://github.com/isc30/blazor-analytics/blob/master/src/Blazor.Analytics/GoogleAnalytics/GoogleAnalyticsStrategy.cs)?

I'm happy to do a PR if changes are needed to make it work.

**Comment by isc30** [comment]
Hi, to be honest I haven't used that feature.
Now that I see it you are right, the int parameter doesn't make sense.
Feel free to open a PR changing that to string :)
