### ISSUE TITLE
Question: For the new GA4 property is the MeasurementID also enough as the GTAG ID?

### ISSUE THREAD

**Issue by wiske80** [isc30/blazor-analytics#37]
Hi,

great package. I was wondering since Google now has the GA4 properties instead of the old Universal Google Analytics ID.

They call it the measurement ID now for GA4. Can i pass that ID now also in this package and does that work?

thanks

**Comment by ErikHen** [comment]
Hi. I have only used it with GA4. So, yes 🙂.

**Comment by Jacko1394** [comment]
Hey guys,

I've created a new GA4 property and followed setup instructions.
I'm using MeasurementID, and all the page_title names are always just the HTML title.

Anyt ideas why?
