### ISSUE TITLE
net6 preview 7

### ISSUE THREAD

**Issue by mikes-gh** [isc30/blazor-analytics#44]
I have the following error on build after upgrading a working app to net 6
IOt is a hosted BSS/wasm app

```
C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(676,7): error : Found conflicting definitions for the same asset 'Identity: C:\Users\mikes.SURCOUF\.nuget\packages\blazor-analytics\3.8.0\contentFiles\any\netstandard2.0\wwwroot\blazor-analytics.js, SourceType: Project, SourceId: MudBlazor.Docs.Client, ContentRoot: C:\Users\mikes.SURCOUF\source\repos\MudBlazor\src\MudBlazor.Docs.Client\wwwroot\, BasePath: wasm, RelativePath: blazor-analytics.js, AssetKind: All, AssetMode: All, AssetRole: Primary, RelatedAsset: , AssetTraitName: , AssetTraitValue: , CopyToOutputDirectory: Never, CopyToPublishDirectory: PreserveNewest, OriginalItemSpec: C:\Users\mikes.SURCOUF\.nuget\packages\blazor-analytics\3.8.0\contentFiles\any\netstandard2.0\wwwroot\blazor-analytics.js' and 'Identity: C:\Users\mikes.SURCOUF\.nuget\packages\blazor-analytics\3.8.0\contentFiles\any\netstandard2.0\wwwroot\blazor-analytics.js, SourceType: Discovered, SourceId: MudBlazor.Docs.Server, ContentRoot: C:\Users\mikes.SURCOUF\source\repos\MudBlazor\src\MudBlazor.Docs.Server\wwwroot\, BasePath: _content/MudBlazor.Docs.Server, RelativePath: blazor-analytics.js, AssetKind: All, AssetMode: All, AssetRole: Primary, RelatedAsset: , AssetTraitName: , AssetTraitValue: , CopyToOutputDirectory: Never, CopyToPublishDirectory: PreserveNewest, 
OriginalItemSpec: C:\Users\mikes.SURCOUF\.nuget\packages\blazor-analytics\3.8.0\contentFiles\any\netstandard2.0\wwwroot\blazor-analytics.js' [C:\Users\mikes.SURCOUF\source\repos\MudBlazor\src\MudBlazor.Docs.Server\MudBlazor.Docs.Server.csproj]
The terminal process "C:\Program Files\PowerShell\7\pwsh.exe -Command dotnet build src/MudBlazor.sln /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary" terminated with exit code: 1.
```

**Comment by CrahunGit** [comment]
Seems and error. I’ve reported it to the asp net core team as you can see. https://github.com/dotnet/aspnetcore/issues/35254

**Comment by CrahunGit** [comment]
At this time we can not fix it because it's a bug on a blazor preview version. If the bug fails on stable version feel free to open it again.

**Comment by CrahunGit** [comment]
Based on aspnet core team I reopen this issue. Js file, css and all statics from razor class library should not be copied in target wwwroot folder. It’s our fault.

**Comment by CrahunGit** [comment]
A workaround you can do is remove the blazor-analytics.js from the wwwroot folder. 
Anyway, this is fixed for the next release and will be released soon.

**Comment by mikes-gh** [comment]
Where do I remove this from.  I already deleted the obj and bin directories from both projects before rebuilding.

**Comment by mikes-gh** [comment]
This project is a hybrid site with hosted wasm site inside a BSS site.  It has seperate wwwroot directories on publish.

**Comment by CrahunGit** [comment]
This file is in wwwroot folder. You have to remove blazor-analytics.js

**Comment by mikes-gh** [comment]
Is this the wwwroot in the publish folder. I have already deleted obj and bin directories

**Comment by CrahunGit** [comment]
Not in the publish one. In the project wwwroot folder instead. Both of them. Try it out.

**Comment by mikes-gh** [comment]
There is no `blazor-analytics.js` in any of our project folders (as expected).  They would be referenced from the _content directory of the package.  In this case the package is referenced by 2 projects.  One BSS and one wasm both hosted on the same aspnetcore site.  This all used to work in net 5.0

The references are in the _Host.cshtml (BSS)
`<script src="_content/Blazor-Analytics/blazor-analytics.js"></script>`
and in the Index.html (wasm)
`<script src="_content/Blazor-Analytics/blazor-analytics.js"></script>`

**Comment by CrahunGit** [comment]
Yes but the old version of this package also copied the the js file in the wwwroot folder. Anyway. Can you share a repo showing the problem?

**Comment by mikes-gh** [comment]
I am the devops for MudBlazor
Here is our project.
```
git clone https://github.com/mikes-gh/MudBlazor.git

git checkout net6
cd src
dotnet build
```

**Comment by CrahunGit** [comment]
Ok, I've checked that the js file is still copying to wwwroot folder on Mudblazor o any other project. I'll investigate how to fix it

**Comment by mikes-gh** [comment]
Have a look at this https://github.com/dotnet/aspnetcore/issues/35590

**Comment by mikes-gh** [comment]
This may well be a bug in preview 7

**Comment by mikes-gh** [comment]
One of my users tried an rc nightly and said it wasnt fixed but I would try aswell if not just to confirm

**Comment by mikes-gh** [comment]
Actually preview7 works fine and your fix is valid.
You have to be careful to delete the `blazor-analytics.js file` in wwwroot via the file manager.  Deleting through VS2022 adds an entry in the csproj file and leaves the underlying file in place.

I can build MudBlazor on VS 2022 and vscode on windows using 3.9.0 once the extra ` blazor-analytics.js` file is removed

So to summarise I think the original problem with the js file ending up in wwwroot is fixed with 3.9.0 on windows.
It seems to be a specific problem on my mac with vscode.
I will continue to investigate and report back.

**Comment by CrahunGit** [comment]
Thanks for your valuable help

**Comment by mikes-gh** [comment]
Just reporting that rc1 in conjunction with the fix is now all ok across all OS and IDE
