### ISSUE TITLE
Add proper disclosure to package

### ISSUE THREAD

**Issue by CoryKoehler** [isc30/blazor-analytics#48]
Hi,

Small ask but can would it be possible to get a disclosure added to the package? I am using this package in a Blazor WASM  app and trying to get google to approve our ads on the site and one of the final hurdles are proper software disclosure on all .dll that the client downloads.

Currently this package is one that is flagged by Google Ads.

Thanks

**Comment by CrahunGit** [comment]
This is a problem regarding browser is downloading dlls. I had the same problem and fixed it with this experimental package. You can check this [here](https://devblogs.microsoft.com/dotnet/custom-deployment-layout-for-blazor-webassembly-apps/)

**Comment by CoryKoehler** [comment]
Hello, I have used the bundler process by microsoft. I still think having a proper disclosure form associated with the package is a good thing.

One reason being that the bundler process is experimental and not fully supported. Another being that the build times with bundler process is quite large.

**Comment by isc30** [comment]
Hi, agreed.
The repository has a `LICENCE.md` file with `MIT` in there, and we can also add `<PackageLicenseExpression>MIT</PackageLicenseExpression>` to the main csproj file.

Let us know if that would solve your issue, thanks! 😄

**Comment by isc30** [comment]
Released as `v3.10.0`

**Comment by CoryKoehler** [comment]
Awesome thank you,

I think what would also help is the following (just taking this from https://github.com/MudBlazor/MudBlazor as they made it through all the flags)

1. In the packaged .csproj a few properties 
```
<PropertyGroup>
    <Version>6.0.2</Version>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageIcon>Nuget.png</PackageIcon>
    <Company>MudBlazor</Company>
    <Authors>Garderoben, Henon and Contributors</Authors>
    <Copyright>Copyright 2021 MudBlazor</Copyright>
    <PackageTags>Blazor, MudBlazor, Material, Material Design, Components, Blazor Components, Blazor Library</PackageTags>
    <Description>MudBlazor is an ambitious Material Design component framework for Blazor with an emphasis on ease of use and clear structure. It is perfect for .NET developers who want to rapidly build web applications without having to struggle with CSS and Javascript. MudBlazor, being written entirely in C#, empowers them to adapt, fix or extend the framework and the multitude of examples in the documentation makes learning MudBlazor very easy.</Description>
    <PackageProjectUrl>http://mudblazor.com/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/MudBlazor/MudBlazor</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE" Pack="true" Visible="false" PackagePath="" />
    <None Include="..\..\content\Nuget.png" Pack="true" Visible="false" PackagePath="" />
  </ItemGroup>
```
2. Contributing.Md
3. Code_Of_Conduct.md
4.  CHANGELOG.md
   1.1 Seems pretty straight fwd can just link to github releases

**Comment by CoryKoehler** [comment]
I can test 3.1.0 out in production and check with google to see if what is currently there is enough. I wish I knew what the bar for approval actually was.

If you want to hold this for a few days till I can get owner approval to do a prod release and go bother google I can circle back early next week

**Comment by isc30** [comment]
@CoryKoehler it's 3.10.0

**Comment by CoryKoehler** [comment]
Sorry yes that is what I have installed - I mistyped
![image](https://user-images.githubusercontent.com/5295679/145715650-0793970f-6186-4291-a74f-0a0f22cdcf5a.png)

**Comment by CoryKoehler** [comment]
I am still currently awaiting to hear back from the google ads team

**Comment by CoryKoehler** [comment]
Hi all - still waiting to hear back from the google ads team

**Comment by CoryKoehler** [comment]
Hi all - got a response back from the team at google and this is now all kosher! Thank you
![image](https://user-images.githubusercontent.com/5295679/147574525-7945d894-215e-4ac2-86dc-d451fda02651.png)

**Comment by isc30** [comment]
Awesome thanks! 👍
