### ISSUE TITLE
Question: Enable for all sites after the first initialization?

### ISSUE THREAD

**Issue by jmjamoin** [isc30/blazor-analytics#56]
I just wanted to ask if its possible to enable the tracking again after initially disabling it. I want to wait on a response from CookieBot if the statistics cookies have been accepted and before that they have to be disabled. 

Thanks!

**Comment by CrahunGit** [comment]
You can use 

```csharp
@inject IAnalytics GlobalTracking

GlobalTracking.Disable();
```

Wherever you need it to enable/disable it on whole App

**Comment by jmjamoin** [comment]
Is it possible to change the tracking behaviour per Client?
Because I was trying to wait for their cookie settings and enable/disable it based on that. Or can I just change it for the whole application - in this case my website - for everyone.
