### ISSUE TITLE
Looks Like its not working for Blazor Web App 8.0

### ISSUE THREAD

**Issue by itkunalce** [isc30/blazor-analytics#67]
Looks Like it's not working for Blazor Web App 8.0

I have created a Blazor web app with both server and web assembly modes.

But it not recorded in analytics.

If you provide one working sample for Blazor web app 8.0 with both server and web assembly in a client project.

**Comment by jamescarter-le** [comment]
I also have this issue on Blazor Server 8.0

I can inject `IAnalytics`, but `NavigationTracker` is never Rendered, nor any events invoked, it does not call `GoogleAnalyticsInterop.configure`.

**Comment by itkunalce** [comment]
Try this way 

`<NavigationTracker @rendermode="InteractiveAuto" />`

![image](https://github.com/user-attachments/assets/8dd0a440-7b08-4864-96fd-c179a36bfb37)

**Comment by itkunalce** [comment]
I have solved in my side by adding @rendermode

**Comment by jamescarter-le** [comment]
Ideally I don't want this to operate in Interative mode, I'd rather it hook into the Enhanced Navigation Blazor events.

**Comment by itkunalce** [comment]
Once you add rendermode then it may start working 

`Analytics.TrackEvent("generate_lead", new {currency = "USD", value = 99.99});`
